# By Harsh H. Rajpurohit
name: vpn_basic_project
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

# App Version
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

# App dependencies
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  cupertino_icons: ^1.0.5
  http: ^1.0.0
  csv: ^5.0.2
  lottie: ^2.4.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0

  # Change package name  
  # change_app_package_name: ^1.1.0

flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/vpn/
    - assets/images/
    - assets/lottie/
    - assets/flags/